//
//  ListPresenter.swift
//  CleanSwift
//
//  Created by Henry on 9/9/17.
//  Copyright (c) 2017 Henry Tsai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListPresentationLogic {
    func presentList(response: List.FetchData.Response)
    func presentTrack(track: MusicAPIFeed.Track)
}

class ListPresenter: ListPresentationLogic {
    weak var viewController: ListDisplayLogic?
    func presentList(response: List.FetchData.Response) {
        DispatchQueue.main.async { [weak self] in
            let viewModel = ListViewController.ViewModel(items: response.tracks.flatMap{$0.toItem()})
            self?.viewController?.displayList(viewModel: viewModel)
        }
    }
    func presentTrack(track: MusicAPIFeed.Track) {
        guard let itemDetailURL = URL(string: track.detailURL) else { return }
        DispatchQueue.main.async { [weak self] in
            self?.viewController?.displayItemDetail(url: itemDetailURL)
        }
    }
}

extension MusicAPIFeed.Track {
    func toItem() -> ListViewController.ViewModel.Item? {
        return ListViewController.ViewModel.Item(itemId: trackId, title: name, subtitle: artistName, imageURL: URL(string: artWorkURL))
    }
}
