//
//  TabNavigationInteractor.swift
//  CleanSwift
//
//  Created by Henry on 9/11/17.
//  Copyright (c) 2017 Henry Tsai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TabNavigationBusinessLogic {
	func initTabs(request: TabNavigation.InitTabs.Request)
}

protocol TabNavigationDataStore { }

class TabNavigationInteractor: TabNavigationBusinessLogic, TabNavigationDataStore {
	var presenter: TabNavigationPresentationLogic?
	var worker: TabNavigationWorker?
  
    func initTabs(request: TabNavigation.InitTabs.Request) {
    	let response = TabNavigation.InitTabs.Response()
    	presenter?.presentTabs(response: response)
    }
}
