//
//  TabNavigationRouter.swift
//  CleanSwift
//
//  Created by Henry on 9/11/17.
//  Copyright (c) 2017 Henry Tsai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol TabNavigationRoutingLogic {
    func initTabs()
}

protocol TabNavigationDataPassing {
	var dataStore: TabNavigationDataStore? { get }
}

class TabNavigationRouter: NSObject {
	weak var viewController: TabNavigationViewController?
	var dataStore: TabNavigationDataStore?
    var viewControllers = [UIViewController]()
}

// MARK: Navigation
extension TabNavigationRouter: TabNavigationRoutingLogic {
    func initTabs() {
        guard let listViewController = UIStoryboard(name: "ListViewController", bundle: nil).instantiateInitialViewController() as? ListViewController else { return }
        guard let collectionViewController = UIStoryboard(name: "TrackCollectionViewController", bundle: nil).instantiateInitialViewController() as? TrackCollectionViewController else { return }
        let tab1 = listViewController
        let tab2 = collectionViewController
        let navigaionControllerForTab1 = UINavigationController(rootViewController: tab1)
        let navigaionControllerForTab2 = UINavigationController(rootViewController: tab2)
        viewControllers = [navigaionControllerForTab1, navigaionControllerForTab2]
        viewController?.viewControllers = viewControllers
        viewController?.tabBar.items?[0].title = "List"
        viewController?.tabBar.items?[0].title = "Collection"
    }
}

// MARK: Passing data
extension TabNavigationRouter : TabNavigationDataPassing {
  
  	//func passDataToSomewhere(source: TabNavigationDataStore, destination: inout SomewhereDataStore) {
	//  destination.name = source.name
	//}
}
