//
//  TabNavigationRouter.swift
//  CleanSwift
//
//  Created by Henry on 9/11/17.
//  Copyright (c) 2017 Henry Tsai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol TabNavigationRoutingLogic: NSObjectProtocol {
    func initTabs()
}

class TabNavigationRouter: NSObject {
	weak var viewController: TabNavigationViewController?
    private var viewControllers = [UIViewController]()
    private var listViewControllerFactory: ListViewControllerFactory
    private var trackCollectionViewControllerFactory: TrackCollectionViewControllerFactory
    init(listViewControllerFactory: ListViewControllerFactory,
         trackCollectionViewControllerFactory: TrackCollectionViewControllerFactory) {
        self.listViewControllerFactory = listViewControllerFactory
        self.trackCollectionViewControllerFactory = trackCollectionViewControllerFactory
    }
}

// MARK: Navigation
extension TabNavigationRouter: TabNavigationRoutingLogic {
    func initTabs() {
        guard let listViewController = listViewControllerFactory.build(),
            let collectionViewController = trackCollectionViewControllerFactory.build()
            else {
                return
        }
        let tab1 = listViewController
        let tab2 = collectionViewController
        let navigaionControllerForTab1 = UINavigationController(rootViewController: tab1)
        let navigaionControllerForTab2 = UINavigationController(rootViewController: tab2)
        viewControllers = [navigaionControllerForTab1, navigaionControllerForTab2]
        viewController?.viewControllers = viewControllers
        viewController?.tabBar.items?[0].title = "List"
        viewController?.tabBar.items?[1].title = "Collection"
    }
}

