//
//  TabNavigationPresenter.swift
//  CleanSwift
//
//  Created by Henry on 9/11/17.
//  Copyright (c) 2017 Henry Tsai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TabNavigationPresentationLogic {
	func presentTabs(response: TabNavigation.InitTabs.Response)
}

class TabNavigationPresenter: TabNavigationPresentationLogic {
	weak var viewController: TabNavigationDisplayLogic?
  
	// MARK: Do something
  
	func presentTabs(response: TabNavigation.InitTabs.Response) {
    	let viewModel = TabNavigationViewController.ViewModel()
    	viewController?.initTabs(viewModel: viewModel)
    }
}
