//
//  RootInteractor.swift
//  CleanSwift
//
//  Created by Henry on 9/10/17.
//  Copyright (c) 2017 Henry Tsai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RootBusinessLogic {
    func initApplication(request: Root.InitApplication.Request)
}

protocol RootDataStore { }

class RootInteractor: RootDataStore {
	var presenter: RootPresentationLogic?
    var entityManager: EntityManager?
}

extension RootInteractor {
    func initPersistence() -> UserData? {
        let initPersistence = PersistenceInitlizeWorker()
        entityManager = initPersistence.initlizePersistence()
        return entityManager?.fetchUserData()
    }
    
    func initWithUserData(userData: UserData) {
        guard let refreshToken = userData.refreshToken else {
            showLogin()
            return
        }
        let performLogin = PerformLoginWorker()
        performLogin.performReauth(userId: userData.userId, refreshToken: refreshToken) {[weak self]  (success, accessToken, refreshToken) -> (Void) in
            if success {
                let newUserData = UserData(userId: userData.userId, accessToken: accessToken, refreshToken: refreshToken)
                self?.entityManager?.saveUserData(userData: newUserData)
                // if user has login show main module
                let response = Root.InitApplication.Response(isUsesrLogin: true)
                self?.presenter?.presentView(response: response)
            } else {
                // if user isn't login show login
                self?.showLogin()
            }
        }
    }
    
    func initWithNoUserData() {
        showLogin()
    }
    
    func showLogin() {
        let response = Root.InitApplication.Response(isUsesrLogin: false)
        presenter?.presentView(response: response)
    }
}

extension RootInteractor: RootBusinessLogic {
    func initApplication(request: Root.InitApplication.Request) {
        if let userData = initPersistence() {
            initWithUserData(userData: userData)
        } else {
            initWithNoUserData()
        }
    }
}
