//
//  RootRouter.swift
//  CleanSwift
//
//  Created by Henry on 9/10/17.
//  Copyright (c) 2017 Henry Tsai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RootRoutingLogic: NSObjectProtocol {
    func routeToLogin()
    func routeToMain()
}

class RootRouter: NSObject {
	weak var viewController: RootViewController?
    var tableBarControllerFactory: TabNavigationViewControllerFactory
    var loginViewControllerFactory: LoginViewControllerFactory

    init(tableBarControllerFactory: TabNavigationViewControllerFactory,
         loginViewControllerFactory: LoginViewControllerFactory) {
        self.tableBarControllerFactory = tableBarControllerFactory
        self.loginViewControllerFactory = loginViewControllerFactory
        super.init()
    }
    
    func removeAllChildViewControllers() {
        viewController?.childViewControllers.forEach({ (viewController) in
            viewController.willMove(toParentViewController: nil)
            viewController.view.removeFromSuperview()
        })
    }
    
    func addChildViewController(childViewController: UIViewController) {
        guard let viewContoller = viewController else { return }
        childViewController.view.frame = viewContoller.view.bounds
        childViewController.willMove(toParentViewController: viewController)
        viewContoller.addChildViewController(childViewController)
        viewContoller.view.addSubview(childViewController.view)
        childViewController.didMove(toParentViewController: viewContoller)
    }
 }

extension RootRouter: RootRoutingLogic {
    func routeToLogin() {
        guard let loginViewController = loginViewControllerFactory.build(routerDelegate: self) else { return }
        removeAllChildViewControllers()
        addChildViewController(childViewController: loginViewController)
    }
    
    func routeToMain() {
        guard let tabNavigationController = tableBarControllerFactory.build() else { return }
        removeAllChildViewControllers()
        addChildViewController(childViewController: tabNavigationController)
    }
}

extension RootRouter: LoginRouterDelegate {
    func loginSuccess() {
        routeToMain()
    }
}
