//
//  RootPresenter.swift
//  CleanSwift
//
//  Created by Henry on 9/10/17.
//  Copyright (c) 2017 Henry Tsai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RootPresentationLogic {
    func presentView(response: Root.InitApplication.Response)
}

class RootPresenter: RootPresentationLogic {
	weak var viewController: RootDisplayLogic?
    func presentView(response: Root.InitApplication.Response) {
        DispatchQueue.main.async { [weak self] in
            if response.isUsesrLogin {
                self?.viewController?.displayMain()
            } else {
                self?.viewController?.displayLogin()
            }
        }
    }
}
