//
//  PerformLoginWorker.swift
//  CleanSwift
//
//  Created by Henry on 9/10/17.
//  Copyright (c) 2017 Henry Tsai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class PerformLoginWorker {
    private(set) var api: API = APIWithMock()
    func performReauth(userId: String, refreshToken: String, completion: @escaping (Bool, String?, String?)->(Void)) {
        print("login in ....")
        let request = APIAuth.Request.refresh(userId: userId, refreshToken: refreshToken)
        api.auth(request: request) { (result) in
            switch result {
            case .success( _, let result):
                completion(true, result.accessToken, result.refreshToken)
                break
            case .error(_, _):
                completion(false, nil, nil)
                break
            }
            print("done login in")
        }
	}
    
    func performLogin(userId: String, password: String, completion: @escaping (Bool, String?, String?)->(Void)) {
        let request = APIAuth.Request.new(userId: userId, password: password)
        api.auth(request: request) { (result) in
            switch result {
            case .success( _, let result):
                completion(true, result.accessToken, result.refreshToken)
                break
            case .error( _, _):
                completion(false, nil, nil)
                break
            }
        }
    }
}
