//
//  PersistenceInitlizeWorker.swift
//  CleanSwift
//
//  Created by Henry on 9/10/17.
//  Copyright (c) 2017 Henry Tsai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class PersistenceInitlizeWorker {
	func initlizePersistence() -> EntityManager {
        print("init persistence.....")
        sleep(1)
        print("done init persistence")
        return EntityManagerWithUserDefault()
	}
}
