//
//  LoginModels.swift
//  CleanSwift
//
//  Created by Henry on 9/9/17.
//  Copyright (c) 2017 Henry Tsai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login {
    // MARK: Use cases
    enum DoLogin {
        struct Request {
            private(set) var userId: String            
            private(set) var password: String
        }
        struct Response {
            var success: Bool
        }
    }
}
