//
//  LoginRouter.swift
//  CleanSwift
//
//  Created by Henry on 9/9/17.
//  Copyright (c) 2017 Henry Tsai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginRouterDelegate: class {
    func loginSuccess()
}

@objc protocol LoginRoutingLogic {
    func loginSuccess()
}

class LoginRouter: NSObject {
    weak var viewController: LoginViewController?
    weak var delegate: LoginRouterDelegate?
}

extension LoginRouter: LoginRoutingLogic {
    func loginSuccess() {
        delegate?.loginSuccess()
    }
}
