//
//  ItemDetailPresenter.swift
//  CleanSwift
//
//  Created by Henry on 9/10/17.
//  Copyright (c) 2017 Henry Tsai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ItemDetailPresentationLogic {
    func presentDetail(response: ItemDetail.DisplayDetail.Response)
}

class ItemDetailPresenter  {
	weak var viewController: ItemDetailDisplayLogic?  
}

extension ItemDetailPresenter: ItemDetailPresentationLogic {
    func presentDetail(response: ItemDetail.DisplayDetail.Response) {
        let viewModel = ItemDetailViewController.ViewModel(url: response.url)
        viewController?.showDetail(viewModel: viewModel)
    }
}

