//
//  ItemDetailRouter.swift
//  CleanSwift
//
//  Created by Henry on 9/10/17.
//  Copyright (c) 2017 Henry Tsai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ItemDetailRoutingLogic { }

protocol ItemDetailDataPassing {
	var dataStore: ItemDetailDataStore? { get }
}

class ItemDetailRouter: NSObject {
	weak var viewController: ItemDetailViewController?
	var dataStore: ItemDetailDataStore?
}

// MARK: Navigation
extension ItemDetailRouter: ItemDetailRoutingLogic { }

// MARK: Passing data
extension ItemDetailRouter : ItemDetailDataPassing { }
