//
//  HomeRouter.swift
//  CleanSwift
//
//  Created by Henry on 9/10/17.
//  Copyright (c) 2017 Henry Tsai. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeRoutingLogic {
    func routeToListView()
}

protocol HomeDataPassing {
	var dataStore: HomeDataStore? { get }
}

class HomeRouter: NSObject, HomeDataPassing {
	weak var viewController: HomeViewController?
	var dataStore: HomeDataStore?
}

extension HomeRouter: HomeRoutingLogic {
    func routeToListView() {
        guard let listViewController = UIStoryboard(name: "ListViewController", bundle: nil).instantiateInitialViewController() as? ListViewController else { return }
        viewController?.viewControllers = [listViewController]
    }
}


